version: '3'
services:
  nxrm:
    container_name: nxrm
    image: sonatype/nexus3
    ports:
      - 18081:8081
  nginx:
    container_name: nginx
    image: bradbeck/nginx-dockerized
    depends_on:
      - nxrm
    ports:
      - 8081:80
    command: [ "dockerize", "-wait", "http://nxrm:8081", "-timeout", "300s", "nginx", "-g", "daemon off;" ]
    volumes:
      - $PWD/proxy.nginx:/etc/nginx/conf.d/default.conf
